"""add medico many-tomany relations

Revision ID: 7133cc373f15
Revises: 8e9bafc9342a
Create Date: 2025-11-05 20:16:59.022344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7133cc373f15'
down_revision: Union[str, Sequence[str], None] = '8e9bafc9342a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_especialidades_id'), 'especialidades', ['id'], unique=False)
    op.create_table('medico_especialidad',
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('especialidad', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('medico_id', 'especialidad')
    )
    op.create_table('medico_hospital',
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitales.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('medico_id', 'hospital_id')
    )
    op.add_column('medicos', sa.Column('telefono', sa.String(), nullable=True))
    op.drop_constraint(op.f('medicos_hospital_id_fkey'), 'medicos', type_='foreignkey')
    op.drop_column('medicos', 'hospital_id')
    op.drop_column('medicos', 'especialidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicos', sa.Column('especialidad', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('medicos', sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('medicos_hospital_id_fkey'), 'medicos', 'hospitales', ['hospital_id'], ['id'])
    op.drop_column('medicos', 'telefono')
    op.drop_table('medico_hospital')
    op.drop_table('medico_especialidad')
    op.drop_index(op.f('ix_especialidades_id'), table_name='especialidades')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
