"""add_telefono_to_coordinadores

Revision ID: 8e87c495bd52
Revises: 037a57260d1a
Create Date: 2025-11-20 22:06:47.229548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e87c495bd52'
down_revision: Union[str, Sequence[str], None] = '037a57260d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asignaciones', 'fecha_asignacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_asignaciones_activo'), table_name='asignaciones')
    op.drop_index(op.f('ix_asignaciones_medico_id'), table_name='asignaciones')
    op.drop_index(op.f('ix_asignaciones_paciente_id'), table_name='asignaciones')
    op.drop_index(op.f('uq_asignacion_activa_por_paciente'), table_name='asignaciones', postgresql_where='(activo = true)')
    op.add_column('coordinadores', sa.Column('telefono', sa.String(), nullable=True))
    op.drop_index(op.f('ix_pacientes_hospital_id'), table_name='pacientes')
    op.drop_constraint(op.f('fk_pacientes_hospital_id'), 'pacientes', type_='foreignkey')
    op.create_foreign_key(None, 'pacientes', 'hospitales', ['hospital_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pacientes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pacientes_hospital_id'), 'pacientes', 'hospitales', ['hospital_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_pacientes_hospital_id'), 'pacientes', ['hospital_id'], unique=False)
    op.drop_column('coordinadores', 'telefono')
    op.create_index(op.f('uq_asignacion_activa_por_paciente'), 'asignaciones', ['paciente_id'], unique=True, postgresql_where='(activo = true)')
    op.create_index(op.f('ix_asignaciones_paciente_id'), 'asignaciones', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_asignaciones_medico_id'), 'asignaciones', ['medico_id'], unique=False)
    op.create_index(op.f('ix_asignaciones_activo'), 'asignaciones', ['activo'], unique=False)
    op.alter_column('asignaciones', 'fecha_asignacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
