"""Initial migration

Revision ID: 8e9bafc9342a
Revises: 8fc8ba6c3e0e
Create Date: 2025-10-30 03:03:23.806147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9bafc9342a'
down_revision: Union[str, Sequence[str], None] = '8fc8ba6c3e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('distrito', sa.String(), nullable=True),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_hospitales_id'), 'hospitales', ['id'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.Enum('masculino', 'femenino', 'otro', name='generoenum'), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('paciente', 'medico', 'coordinador', 'admin', name='rolenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_documento'), 'pacientes', ['documento'], unique=True)
    op.create_index(op.f('ix_pacientes_email'), 'pacientes', ['email'], unique=True)
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_table('coordinadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('rol', sa.Enum('paciente', 'medico', 'coordinador', 'admin', name='rolenum'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coordinadores_documento'), 'coordinadores', ['documento'], unique=True)
    op.create_index(op.f('ix_coordinadores_email'), 'coordinadores', ['email'], unique=True)
    op.create_index(op.f('ix_coordinadores_id'), 'coordinadores', ['id'], unique=False)
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('especialidad', sa.String(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('rol', sa.Enum('paciente', 'medico', 'coordinador', 'admin', name='rolenum'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicos_documento'), 'medicos', ['documento'], unique=True)
    op.create_index(op.f('ix_medicos_email'), 'medicos', ['email'], unique=True)
    op.create_index(op.f('ix_medicos_id'), 'medicos', ['id'], unique=False)
    op.create_table('asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_id'), 'asignaciones', ['id'], unique=False)
    op.create_table('formularios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('preguntas', sa.JSON(), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formularios_id'), 'formularios', ['id'], unique=False)
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('leido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_id'), 'mensajes', ['id'], unique=False)
    op.create_table('respuestas_formularios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('respuestas', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respuestas_formularios_id'), 'respuestas_formularios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_respuestas_formularios_id'), table_name='respuestas_formularios')
    op.drop_table('respuestas_formularios')
    op.drop_index(op.f('ix_mensajes_id'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_formularios_id'), table_name='formularios')
    op.drop_table('formularios')
    op.drop_index(op.f('ix_asignaciones_id'), table_name='asignaciones')
    op.drop_table('asignaciones')
    op.drop_index(op.f('ix_medicos_id'), table_name='medicos')
    op.drop_index(op.f('ix_medicos_email'), table_name='medicos')
    op.drop_index(op.f('ix_medicos_documento'), table_name='medicos')
    op.drop_table('medicos')
    op.drop_index(op.f('ix_coordinadores_id'), table_name='coordinadores')
    op.drop_index(op.f('ix_coordinadores_email'), table_name='coordinadores')
    op.drop_index(op.f('ix_coordinadores_documento'), table_name='coordinadores')
    op.drop_table('coordinadores')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_email'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_documento'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_hospitales_id'), table_name='hospitales')
    op.drop_table('hospitales')
    # ### end Alembic commands ###
