"""add remitente_rol en mensajes

Revision ID: b582bf9c2697
Revises: 865a44561ffb
Create Date: 2026-02-10 21:59:55.028007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b582bf9c2697'
down_revision: Union[str, Sequence[str], None] = '865a44561ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formulario_asignaciones_estado'), table_name='formulario_asignaciones')
    op.add_column('mensajes', sa.Column('remitente_rol', sa.Enum('paciente', 'medico', 'coordinador', 'admin', name='rolenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensajes', 'remitente_rol')
    op.create_index(op.f('ix_formulario_asignaciones_estado'), 'formulario_asignaciones', ['estado'], unique=False)
    # ### end Alembic commands ###
