"""convert especialidades to catalog table with many-to-many

Revision ID: f010e78ee8f4
Revises: 7133cc373f15
Create Date: 2025-11-05 21:59:57.722741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f010e78ee8f4'
down_revision: Union[str, Sequence[str], None] = '7133cc373f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('especialidades', sa.Column('activa', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('especialidades_nombre_key'), 'especialidades', type_='unique')
    op.create_index(op.f('ix_especialidades_nombre'), 'especialidades', ['nombre'], unique=True)
    op.add_column('medico_especialidad', sa.Column('especialidad_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'medico_especialidad', 'especialidades', ['especialidad_id'], ['id'])
    op.drop_column('medico_especialidad', 'especialidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medico_especialidad', sa.Column('especialidad', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'medico_especialidad', type_='foreignkey')
    op.drop_column('medico_especialidad', 'especialidad_id')
    op.drop_index(op.f('ix_especialidades_nombre'), table_name='especialidades')
    op.create_unique_constraint(op.f('especialidades_nombre_key'), 'especialidades', ['nombre'], postgresql_nulls_not_distinct=False)
    op.drop_column('especialidades', 'activa')
    # ### end Alembic commands ###
